version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
    # logstash-logback-encoder >= v7.4 requires logback v2,
    # but Alpine is still using logback v1. Do not suggest
    # updates beyond v7.3.x for now.
    - dependency-name: logstash-logback-encoder
      update-types:
      - version-update:semver-major
      - version-update:semver-minor
    # logback-classic 1.3.x requires SLF4J 2.x, but SLF4J 2.x breaks datanucleus-maven-plugin.
    # logback-classic 1.4.x uses Jakarta EE namespace whereas Alpine is still on legacy Java EE.
    - dependency-name: ch.qos.logback:logback-classic
      update-types:
      - version-update:semver-major
      - version-update:semver-minor

  - package-ecosystem: "maven"
    directory: "/executable-war/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "maven"
    directory: "/example/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
