version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
    # logstash-logback-encoder >= v7.4 requires logback v2,
    # but Alpine is still using logback v1. Do not suggest
    # updates beyond v7.3.x for now.
    - dependency-name: logstash-logback-encoder
      update-types:
      - version-update:semver-major
      - version-update:semver-minor

  - package-ecosystem: "maven"
    directory: "/executable-war/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "maven"
    directory: "/example/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
