name: Maven Release

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          # Export the gpg private key using the following command and add the contents of that file to the GitHub secret
          # gpg --armor --export-secret-keys <key_id> > gpg_key.asc
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Set up git
        run: |
          git config --global user.email "steve@springett.us"
          git config --global user.name "Steve Springett"
          git config --global credential.helper 'store --file ~/.git-credentials'
          echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials

      - name: Release package
        # This requires the connection and developerConnection elements in the scm section of the pom
        # to be set to "scm:git:https:...." thus preventing the release plugin from using SSH.
        run: mvn -B release:clean release:prepare release:perform -Prelease
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
